[pytest]
testpaths = tests_pytest
pythonpath = .
addopts = -n auto --reruns 2 --reruns-delay 1 --alluredir=reports/allure-results
markers =
    login: 登录相关测试
    alert: 弹窗相关测试
    select: 下拉框相关测试
    checkbox: 复选框相关测试
    table: 表格相关测试
    wait: 显式等待相关测试
    smoke: 冒烟测试
    textarea: 文本框相关测试
    message: 消息相关测试
    advanced: 高级 Selenium 操作相关测试
